import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdad4",
        "on-secondary-container": "#64635c",
        "surface-container": "#f0eded",
        "surface-variant": "#e4e2e1",
        "on-surface-variant": "#5a403c",
        "surface-container-high": "#eae7e7",
        "on-primary-container": "#ff907f",
        "inverse-surface": "#303030",
        background: "#fcf9f8",
        "tertiary-fixed": "#ffe088",
        "secondary-fixed": "#e5e2da",
        "secondary-fixed-dim": "#c9c6be",
        "on-tertiary-container": "#4f3e00",
        tertiary: "#735c00",
        "on-secondary-fixed-variant": "#474741",
        surface: "#fcf9f8",
        "surface-container-highest": "#e4e2e1",
        primary: "#610000",
        "inverse-primary": "#ffb4a8",
        "primary-fixed-dim": "#ffb4a8",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1c1c17",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#fcf9f8",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#574500",
        "on-error": "#ffffff",
        "on-primary-fixed": "#410000",
        secondary: "#5f5f58",
        "surface-dim": "#dcd9d9",
        error: "#ba1a1a",
        "secondary-container": "#e2e0d7",
        "tertiary-container": "#cca730",
        "error-container": "#ffdad6",
        "surface-tint": "#b52619",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#e9c349",
        "on-error-container": "#93000a",
        "outline-variant": "#e3beb8",
        outline: "#8e706b",
        "surface-container-low": "#f6f3f2",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-fixed-variant": "#920703",
        "primary-container": "#8b0000",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.5", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms],
};
